# Generated by Django 3.1.7 on 2021-03-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0002_auto_20210312_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='musicdb.users'),
        ),
    ]
