# Generated by Django 3.1.7 on 2021-03-15 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0004_auto_20210315_2144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('username', 'song')},
        ),
    ]
