# Generated by Django 3.1.7 on 2021-03-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0005_auto_20210315_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratings',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.users'),
        ),
    ]
