# Generated by Django 3.1.7 on 2021-03-17 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0006_auto_20210315_2155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000)),
                ('president', models.CharField(max_length=50)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.songs')),
            ],
        ),
    ]
