# Generated by Django 3.1.7 on 2021-05-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0007_auto_20210317_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
