# Generated by Django 3.1.7 on 2021-05-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0010_auto_20210517_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='unit_id',
            new_name='id',
        ),
    ]
