# Generated by Django 3.1.7 on 2021-05-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0011_auto_20210517_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='cole',
        ),
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
