# Generated by Django 3.1.7 on 2021-05-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0012_auto_20210517_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='id',
        ),
        migrations.AddField(
            model_name='ratings',
            name='my_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
