# Generated by Django 3.1.7 on 2021-05-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0008_auto_20210517_2128'),
        ('musicdb', '0013_auto_20210517_2149'),
    ]

    operations = [
    ]
